version: '3.3'
services: 
    db:
        image: 'postgres'
        container_name: "postgres"
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_DB=postgresql
          - POSTGRES_PASSWORD=securepass
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - '5432:5432'
    libraryiot:
        build:
          context: ./libraryiot
          dockerfile: Dockerfile
        ports: 
          - "8000:8000"
        depends_on: 
          - db